image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
  - init: npm install
  - command: echo 'start script'
  - command: ./node_modules/ionic/bin/ionic server -- --disable-host-check

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker@1.7.18:B/ZdCj+T7LBpijGDIhNE5g==
    - eamodio.gitlens@10.1.1:W/mM/phTCRJ9XghzvZRI4g==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==